### ISSUE TITLE
Cannot download Face Mask Detection.zip

### ISSUE THREAD

**Issue by coderjoonwoo** [Pseudo-Lab/Tutorial-Book-DataLoader#3]
Accessing 'https://drive.google.com/uc?id=1pJtohTc9NGNRzHj5IsySR39JIRPfkgD3' only causes web page error 404.
What did I do wrong?

**Comment by sucong2** [comment]
> Accessing 'https://drive.google.com/uc?id=1pJtohTc9NGNRzHj5IsySR39JIRPfkgD3' only causes web page error 404. What did I do wrong?

ME TOO!!

**Comment by SDSTony** [comment]
Hello @coderjoonwoo and @sucong2, the issue has now been resolved. Could you please try going through the tutorial again?
